# Generated by Django 4.1.7 on 2023-04-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_format",
                    models.JSONField(
                        help_text="You should use http://json-schema.org to create the format for the expected data."
                    ),
                ),
            ],
        ),
    ]
