# Generated by Django 4.1.7 on 2023-04-06 12:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_template", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="data_format",
            field=models.JSONField(
                default={
                    "$schema": "http://json-schema.org/draft-07/schema#",
                    "properties": {
                        "eventData": {
                            "properties": {
                                "price": {"minimum": 1, "type": "integer"},
                                "productId": {"minimum": 1, "type": "integer"},
                                "quantity": {"minimum": 1, "type": "integer"},
                            },
                            "type": "object",
                        },
                        "eventType": {"enum": ["purchase"], "type": "string"},
                        "userId": {"minimum": 1, "type": "integer"},
                    },
                    "required": ["userId", "eventType", "eventData"],
                    "type": "object",
                },
                help_text="To learn more about json-schema visit http://json-schema.org",
            ),
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55)),
                (
                    "type",
                    models.CharField(
                        choices=[("integer", "Number"), ("string", "Char")],
                        default="string",
                        max_length=50,
                    ),
                ),
                ("is_choice_field", models.BooleanField(default=False)),
                (
                    "choices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        size=None,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="dynamic_template.template",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
