# Generated by Django 4.1.7 on 2023-04-06 13:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_template", "0002_alter_template_data_format_templatefield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatefield",
            name="choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=["example", "anotherexample"],
                help_text="Don't use unwanted spaces.",
                size=None,
            ),
        ),
    ]
