# Generated by Django 4.1.7 on 2023-04-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_template", "0004_templatenestedfield_templatefield_nested"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="templatefield",
            options={"verbose_name": "Field", "verbose_name_plural": "Fields"},
        ),
        migrations.AlterModelOptions(
            name="templatenestedfield",
            options={
                "verbose_name": "Nested field",
                "verbose_name_plural": "Nested fields",
            },
        ),
        migrations.AlterField(
            model_name="templatenestedfield",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nested_fields",
                to="dynamic_template.template",
            ),
        ),
    ]
