# Generated by Django 4.1.7 on 2023-04-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_template", "0005_alter_templatefield_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutbondRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="template",
            name="data_format",
        ),
        migrations.AddField(
            model_name="template",
            name="name",
            field=models.CharField(default="Tema", max_length=200),
            preserve_default=False,
        ),
    ]
