# Generated by Django 4.1.7 on 2023-04-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dynamic_template",
            "0006_outbondrequest_remove_template_data_format_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="outbondrequest",
            name="data_format",
            field=models.JSONField(
                default={
                    "price": "{eventData.price}",
                    "productId": "{eventData.productId}",
                    "quantity": "{eventData.quantity}",
                    "userId": "{userId}",
                }
            ),
        ),
        migrations.AddField(
            model_name="outbondrequest",
            name="template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="dynamic_template.template",
            ),
            preserve_default=False,
        ),
    ]
