# Generated by Django 4.1.7 on 2023-04-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_template", "0007_outbondrequest_data_format_outbondrequest_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outbondrequest",
            name="data_format",
        ),
        migrations.AddField(
            model_name="outbondrequest",
            name="data_shape",
            field=models.TextField(
                default='{\n        "userId": {{userId}},\n        "productId": {{eventData.productId}},\n        "quantity": {{eventData.quantity}},\n        "price": {{eventData.price}},\n    }'
            ),
        ),
    ]
