# Generated by Django 4.1.7 on 2023-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_template", "0008_remove_outbondrequest_data_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outbondrequest",
            name="data_shape",
            field=models.TextField(
                default='{\n        "userId": {{userId}},\n        "productId": {{eventData.productId}},\n        "quantity": {{eventData.quantity}},\n        "price": {{eventData.price}}\n    }'
            ),
        ),
    ]
