# Generated by Django 4.1.7 on 2023-04-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_template", "0009_alter_outbondrequest_data_shape"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outbondrequest",
            old_name="data_shape",
            new_name="payload",
        ),
        migrations.AddField(
            model_name="outbondrequest",
            name="headers",
            field=models.JSONField(default={"Content-Type": "application/json"}),
        ),
    ]
