# Generated by Django 4.1.7 on 2023-04-06 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_template", "0010_rename_data_shape_outbondrequest_payload_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outbondrequest",
            old_name="payload",
            new_name="payload_format",
        ),
    ]
