# Generated by Django 4.1.7 on 2023-04-06 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_template", "0011_rename_payload_outbondrequest_payload_format"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OutbondRequest",
            new_name="Outbond",
        ),
    ]
